apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: nmap-upstream
  namespace: "{{ .Values.namespace }}"
spec:
  interval: 1h
  image: ghcr.io/instrumentisto/nmap:latest
  proxy:
    httpProxy:  "{{ .Values.proxy.http }}"
    httpsProxy: "{{ .Values.proxy.https }}"
    noProxy:    "{{ .Values.proxy.noProxy }}"
