apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: t50-upstream
  namespace: "{{ .Values.namespace }}"
spec:
  interval: 1h
  image: docker.io/corfr/t50:latest
  proxy:
    httpProxy:  "{{ .Values.proxy.http }}"
    httpsProxy: "{{ .Values.proxy.https }}"
    noProxy:    "{{ .Values.proxy.noProxy }}"
