enabled: true
image:
  repository: anchore/cli
  tag: latest
  pullPolicy: {{ .Values.imagePullPolicy }}

# Registry credentials for pulling target images
imagePullSecrets:
  - name: registry-credentials

# Anchore Engine API credentials (if using standalone Engine)
anchore:
  endpoint: "https://anchore-engine.security-scans.svc.cluster.local:8228/v1"
  user: "${ANCHORE_USER}"
  password: "${ANCHORE_PASS}"

# Cron schedule (runs via Argo CronWorkflow, but kept for standalone helm use)
schedule: "0 4 1 * *"
