apiVersion: batch/v1
kind: Job
metadata:
  name: invicti-scan
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: scan-runner-sa
      containers:
        - name: invicti-cli
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Run Invicti DAST against the target URL
              invicti-cli scan --target {{ .Values.invicti.targetUrl }} \
                --format {{ .Values.invicti.outputFormat }} \
                --output {{ .Values.invicti.outputFilename }}
          env:
            {{- if .Values.global.proxy.enabled }}
            - name: HTTP_PROXY
              value: "{{ .Values.global.proxy.httpProxy }}"
            - name: HTTPS_PROXY
              value: "{{ .Values.global.proxy.httpsProxy }}"
            - name: NO_PROXY
              value: "{{ .Values.global.proxy.noProxy }}"
            {{- end }}
          volumeMounts:
            - name: reports
              mountPath: /reports
      restartPolicy: Never
      volumes:
        - name: reports
          persistentVolumeClaim:
            claimName: scan-reports-pvc
