apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-bench
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kube-bench
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: "{{ .Values.image.pullPolicy }}"
              args:
                - "--json"
                - "--output"
                - "/reports/kube-bench-$(date +%%F).json"
              volumeMounts:
                - name: reports
                  mountPath: /reports
              {{- if .Values.global.proxy.enabled }}
              env:
                - name: HTTP_PROXY    
                  value: "{{ .Values.global.proxy.httpProxy }}"
                - name: HTTPS_PROXY   
                  value: "{{ .Values.global.proxy.httpsProxy }}"
                - name: NO_PROXY      
                  value: "{{ .Values.global.proxy.noProxy }}"
              {{- end }}
          restartPolicy: OnFailure
          volumes:
            - name: reports
              persistentVolumeClaim:
                claimName: scan-reports-pvc
