apiVersion: batch/v1
kind: CronJob
metadata:
  name: pentest-nmap
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: scan-runner-sa
          containers:
            - name: nmap-scan
              image: "{{ .Values.image.nmap.repository }}:{{ .Values.image.nmap.tag }}"
              imagePullPolicy: "{{ .Values.image.nmap.pullPolicy }}"
              args:
                - "-sV"
                - "{{ .Values.pentest.targetHost }}"
              {{- if .Values.global.proxy.enabled }}
              env:
                - name: HTTP_PROXY    
                  value: "{{ .Values.global.proxy.httpProxy }}"
                - name: HTTPS_PROXY   
                  value: "{{ .Values.global.proxy.httpsProxy }}"
                - name: NO_PROXY      
                  value: "{{ .Values.global.proxy.noProxy }}"
              {{- end }}
              volumeMounts:
                - name: reports
                  mountPath: /reports
          restartPolicy: OnFailure
          volumes:
            - name: reports
              persistentVolumeClaim:
                claimName: scan-reports-pvc
