apiVersion: batch/v1
kind: Job
metadata:
  name: nessus-scan
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: scan-runner-sa
      containers:
        - name: nessus-cli
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Run Nessus scan
              nessuscli --host $NESSUS_HOST \
                --username $NESSUS_USER --password $NESSUS_PASS \
                --scan-policy '{{ .Values.nessus.policy }}' \
                --target $TARGET_IMAGE \
                --format '{{ .Values.nessus.format }}' \
                --output /reports/nessus-$(date +"%Y-%m-%d").html
          env:
            - name: NESSUS_HOST
              valueFrom:
                secretKeyRef:
                  name: nessus-credentials
                  key: host
            - name: NESSUS_USER
              valueFrom:
                secretKeyRef:
                  name: nessus-credentials
                  key: user
            - name: NESSUS_PASS
              valueFrom:
                secretKeyRef:
                  name: nessus-credentials
                  key: pass
            - name: TARGET_IMAGE
              value: "harbor-harbor-core.ncms.svc/cfxztstenant/corepaas-docker-local.artifactory-blr1.int.net.nokia.com/dnt-sa-timescaledb:latest"
            {{- if .Values.global.proxy.enabled }}
            - name: HTTP_PROXY
              value: "{{ .Values.global.proxy.httpProxy }}"
            - name: HTTPS_PROXY
              value: "{{ .Values.global.proxy.httpsProxy }}"
            - name: NO_PROXY
              value: "{{ .Values.global.proxy.noProxy }}"
            {{- end }}
          volumeMounts:
            - name: reports
              mountPath: /reports
      restartPolicy: Never
      volumes:
        - name: reports
          persistentVolumeClaim:
            claimName: scan-reports-pvc
